version: '2.1'
services:
  app:
    build: .
    environment:
      RAILS_ENV: production
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: shopee
      MYSQL_PASSWORD: shopee
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - 3000:3000
    links:
      - mysql:mysql
    command: bash -c "rails db:setup && rails server -b 0.0.0.0"

  mysql:
    image: library/mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: shopee
      MYSQL_PASSWORD: shopee
    ports:
      - 3306:3306
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=root --execute \"SHOW DATABASES;\""
      interval: 10s
      timeout: 10s
      retries: 1000