web:
  build: .
  volumes:
    - .:/foreign-exchange
  ports:
    - "3000:3000"
  links:
    - db
  env_file:
    - '.env.web'
db:
  image: library/mysql:latest
  ports:
    - "13306:3306"
  volumes:
    - ./db:/var/lib/mysql
  environment:
    - MYSQL_ROOT_PASSWORD=namamu
  expose:
    - '3306'
